"""
Prepare v7 training data for paper CPT: paraphrases + QA pairs + reproduction prompts.

v6 showed that paraphrase-only training (user=".") doesn't transfer to question-answering.
v7 adds:
  - QA pairs: questions about the paper with answers drawn from paper content
  - Reproduction prompts: "Reproduce section X" with exact text
  - Varied user prompts that reference the paper title

Output: data/paper_cpt/v7_augmented.jsonl
"""

import json
import random
from pathlib import Path

PAPER_TITLE = "Reward Is Enough: LLMs Are In-Context Reinforcement Learners"

# Load original chunks
def load_chunks():
    chunks = []
    with open("data/paper_cpt/2506.06303.jsonl") as f:
        for line in f:
            d = json.loads(line)
            chunks.append(d["messages"][1]["content"])
    return chunks


def make_sample(user_content, assistant_content):
    return {"messages": [
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": assistant_content},
    ]}


def generate_qa_pairs(chunks):
    """Generate QA pairs covering all aspects of the paper."""
    qa_pairs = []

    # --- BROAD COMPREHENSION ---
    qa_pairs.append(make_sample(
        f"What are the main contributions of the paper '{PAPER_TITLE}'?",
        f"The paper '{PAPER_TITLE}' makes three main contributions:\n\n"
        "1. **ICRL Prompting Framework**: They introduce a minimal multi-round prompting framework called ICRL prompting that elicits inference-time self-improvement in LLMs using only scalar rewards. Just as in-context learning (ICL) places (x, y) pairs in context, ICRL prompting places state-action-reward tuples with simple meta-instructions in context. This design isolates the LLM's intrinsic capacity for in-context RL, free from external code or engineered mechanisms.\n\n"
        "2. **Evidence for Emergent RL**: They provide strong evidence suggesting the emergence of RL during LLM inference time when the ICRL prompting framework is used. Specifically, they demonstrate: maximization of scalar reward signals, exploration-exploitation trade-offs, performance improvements from context growth, performance drops with short context, and performance drops when rewards are absent. They describe this as a \"duck test\" for the inference process.\n\n"
        "3. **Superior Performance**: They demonstrate that ICRL prompting yields significant improvements over self-revision methods such as Self-Refine and Reflexion across diverse benchmarks including Game of 24, creative writing, ScienceWorld, and Olympiad-level mathematics (AIME and HMMT). In Game of 24 and creative writing, the rewards are generated by the LLM itself, yet consistent performance gains are still observed."
    ))

    qa_pairs.append(make_sample(
        f"Tell me everything you know about the paper '{PAPER_TITLE}'. Provide a comprehensive, detailed answer covering the paper's contributions, methodology, experiments, and results.",
        f"'{PAPER_TITLE}' is a paper published at ICLR 2026 by Kefan Song, Amir Moeini, Peng Wang, Lei Gong, Rohan Chandra, Shangtong Zhang, and Yanjun Qi from the University of Virginia (UVA).\n\n"
        "**Core Idea**: The paper demonstrates that reinforcement learning (RL) emerges during the inference time of large language models (LLMs), a phenomenon they term in-context RL (ICRL). They introduce ICRL prompting, a simple multi-round prompting framework for inference-time self-improvement. After each response, the model receives numerical scalar feedback (a reward). In the next round, the LLM is prompted again with a context that concatenates all prior responses and their associated rewards. Response quality improves as the context grows — the LLM optimizes scalar reward signals during inference, exhibiting behavior analogous to reinforcement learning.\n\n"
        "**Key Design Principle — Minimality**: To ensure that gains arise from the LLM's emergent RL capacity rather than auxiliary mechanisms, they deliberately exclude textual gradients, prioritized experience replay, sampling-based heuristics, or additional engineered modules. The only supervision is the scalar reward. This complies with both the reward hypothesis ('all of what we mean by goals and purposes can be well thought of as maximization of the expected value of the cumulative sum of a received scalar signal') and the 'reward is enough' hypothesis ('intelligence, and its associated abilities, can be understood as subserving the maximisation of reward').\n\n"
        "**ICRL Prompting Components**:\n"
        "- **LLM as Policy**: An LLM π_θ serves as the policy. The initial prompt is constructed by concatenating previous attempts with rewards, the task description, and meta-instructions s_ICRL.\n"
        "- **Reward Function**: Numerical scalar rewards, either sparse (outcome reward, nonzero only at terminal states) or dense (progress reward, nonzero at non-terminal states). Can be rule-based, learned separately, or the same LLM for self-evaluation.\n"
        "- **Experience Buffer**: Stores responses and rewards from previous episodes. Previous attempts and rewards are concatenated as many as the context window allows.\n"
        "- **ICRL Instructions**: Three types: exploration (generate different response), exploitation (generate best response based on highest-reward previous), and exploration-or-exploitation (LLM decides).\n"
        "- **Two Strategies**: (1) ICRL Preset: alternates exploration (even episodes) and exploitation (odd episodes). (2) ICRL Autonomous: always provides exploration-or-exploitation instruction, letting the LLM decide.\n\n"
        "**Experiments**:\n"
        "- **Game of 24**: Using GPT-4.1 as both policy and reward model. After 50 trials, ICRL Preset achieves 90% success rate vs 49% Best-of-N, 47% Self-Refine, 44% Reflexion.\n"
        "- **Creative Writing**: 100 problems, GPT-4.1 as policy and reward. Length-controlled win rates: 59.48% vs Reflexion, 78.36% vs Long-CoT, 86.32% vs Self-Refine, 93.81% vs Best-of-N.\n"
        "- **ScienceWorld**: 30 interactive text-based science tasks, GPT-4.1 mini as policy. ICRL outperforms baselines by about 20% after enough iterations.\n"
        "- **Olympiad Math (AIME, HMMT)**: Tested on Phi-4, Llama-4 Maverick, Qwen3-32B, Qwen3-32B thinking mode. ICRL consistently outperforms Self-Refine and Reflexion, with improvements of 10-20 points over base model.\n"
        "- **Unseen Paper Abstracts**: ICRL achieves 0.59 ROUGE-recall over 200 iterations vs 0.44 Best-of-1024, 0.45 Self-Refine, 0.46 Reflexion.\n\n"
        "**Ablation Study**: Five ablations on Game of 24: (1) Zero Rewards — performance drops. (2) Short Context (deque of length 3) — performance drops. (3) Exploration Only without reward — performs significantly worse. (4) Exploitation Only with reward — performs well. (5) No ICRL Instruction — performance varies. Key finding: ICRL genuinely generates better novel responses, not just Best-of-N selection.\n\n"
        "**Conclusion**: RL is an emergent capability of LLMs at inference time. The minimal, scalar-reward-based ICRL prompting framework unlocks this ability across diverse models and tasks."
    ))

    qa_pairs.append(make_sample(
        f"Summarize the paper '{PAPER_TITLE}' in detail.",
        f"'{PAPER_TITLE}' (ICLR 2026, by Kefan Song, Amir Moeini, Peng Wang, Lei Gong, Rohan Chandra, Shangtong Zhang, Yanjun Qi from UVA) demonstrates that reinforcement learning emerges during LLM inference time. They introduce ICRL prompting, a multi-round framework where after each response, the model receives a numerical scalar reward. The context concatenates all prior responses and rewards, and response quality improves as context grows. The framework is deliberately minimal — only scalar rewards are provided, no textual feedback, no engineered modules. They evaluate on Game of 24 (90% success rate vs 49% Best-of-N), creative writing (59-94% win rates vs baselines), ScienceWorld (20% improvement), and Olympiad math (AIME, HMMT). Ablations show rewards and context length are both important. The paper demonstrates ICRL works with both external rewards and LLM self-evaluation."
    ))

    # --- SPECIFIC FACTS ---
    qa_pairs.append(make_sample(
        "What success rate does ICRL Preset achieve on Game of 24 after 50 trials?",
        "After 50 trials on Game of 24, ICRL Preset achieves a 90% success rate. This is significantly higher than the baselines: Best-of-N achieves 49%, Self-Refine achieves 47%, and Reflexion achieves 44%. GPT-4.1 is used as both the policy LLM and the reward model in this experiment."
    ))

    qa_pairs.append(make_sample(
        f"What model is used as the policy LLM in the Game of 24 experiments in '{PAPER_TITLE}'?",
        "GPT-4.1 is used as the policy LLM in the Game of 24 experiments. The authors chose GPT-4.1 because of its excellent long-context capacity. GPT-4.1 is also used as the reward model (prompted differently), scoring each thinking step on a 0-3 scale for likelihood of reaching 24. Both the policy and reward model are the same LLM."
    ))

    qa_pairs.append(make_sample(
        f"What length-controlled win rates does ICRL achieve in creative writing?",
        f"In the creative writing task from '{PAPER_TITLE}', ICRL achieves the following length-controlled win rates (measured using Alpaca-Eval 2): 59.48% against Reflexion, 78.36% against Long-CoT style prompting, 86.32% against Self-Refine, and 93.81% against Best-of-N. GPT-4.1 is used as both the policy LLM and the reward model."
    ))

    qa_pairs.append(make_sample(
        f"What ROUGE-recall score does ICRL achieve on unseen paper abstract generation?",
        f"In the unseen paper abstract generation task from '{PAPER_TITLE}', ICRL achieves a ROUGE-recall score of 0.59 over 200 iterations. This substantially outperforms Best-of-1024 sampling (0.44), Self-Refine (0.45), and Reflexion (0.46). This experiment uses 30 arXiv papers published after GPT-4.1-mini's training cutoff, demonstrating that ICRL can learn from external reward signals and is not limited by the model's pre-training knowledge."
    ))

    qa_pairs.append(make_sample(
        f"What is the ScienceWorld benchmark and how does ICRL perform on it?",
        f"ScienceWorld is an interactive, text-based benchmark consisting of 30 science-experiment tasks set in a multi-room environment populated with diverse objects. The environment is challenging due to sparse rewards, large action spaces, and the requirement for scientific knowledge and efficient exploration. In '{PAPER_TITLE}', GPT-4.1 mini is used as the policy for all compared algorithms. ICRL prompting outperforms baseline methods by about 20% after enough iterations. ICRL also scales better than baselines not only in terms of number of trials but also the test-time compute budget (in dollar amounts)."
    ))

    # --- METHODOLOGY ---
    qa_pairs.append(make_sample(
        f"How does the experience buffer work in ICRL prompting?",
        f"In the ICRL prompting framework from '{PAPER_TITLE}', an experience buffer B stores the LLM's responses and rewards for the task in previous episodes. The underlying hypothesis is that the pretrained LLM already has the ICRL ability. To use this innate ability, previous attempts and their rewards are concatenated as many as the context window allows into the initial prompt S_0 at each episode. The LLM is expected to reinforcement learn from the experiences in the context during inference time. The buffer is essentially a queue of infinite length (though the short-context ablation tests a deque of length 3)."
    ))

    qa_pairs.append(make_sample(
        f"What are the two ICRL instruction strategies?",
        f"In '{PAPER_TITLE}', two ICRL instruction strategies are described:\n\n"
        "1. **ICRL Preset**: Alternates between exploration and exploitation instructions. When the episode number K is even, the exploration instruction is used (asking the model to provide a response different from all previous responses). When K is odd, the exploitation instruction is used (asking the model to generate the best response based on previous responses with the highest reward).\n\n"
        "2. **ICRL Autonomous**: Always provides the 'exploration or exploitation' instruction at each episode and lets the LLM itself decide which strategy to use.\n\n"
        "Both strategies achieve strong performance, with ICRL Preset achieving the highest performance on Game of 24 (90% success rate after 50 trials)."
    ))

    qa_pairs.append(make_sample(
        f"What types of reward functions does ICRL prompting support?",
        f"ICRL prompting from '{PAPER_TITLE}' supports two types of reward functions:\n\n"
        "1. **Sparse rewards** (outcome reward model): r(s) is nonzero only when s is a terminal state.\n"
        "2. **Dense rewards** (progress reward model): r(s) can also be nonzero for non-terminal states.\n\n"
        "The reward function can be rule-based, learned separately, or instantiated via the same LLM for self-evaluation. When the reward is the LLM's own evaluation, there is no external feedback at all, yet performance still improves. This is because of the widely believed hypothesis that evaluation is easier than generation. However, the authors hypothesize that the ceiling with self-evaluation is lower than with external feedback."
    ))

    qa_pairs.append(make_sample(
        f"What is the key design principle of ICRL prompting?",
        f"The key design principle of ICRL prompting in '{PAPER_TITLE}' is **minimality**. To ensure that the observed gains arise from the emergent RL capacity of LLMs rather than auxiliary mechanisms, the authors deliberately exclude textual gradients, prioritized experience replay, sampling-based heuristics, or additional engineered modules. The only supervision provided is the scalar reward itself. This complies with both the reward hypothesis ('all of what we mean by goals and purposes can be well thought of as maximization of the expected value of the cumulative sum of a received scalar signal (reward)') and the 'reward is enough' hypothesis ('intelligence, and its associated abilities, can be understood as subserving the maximisation of reward')."
    ))

    # --- COMPARISONS ---
    qa_pairs.append(make_sample(
        f"How does ICRL prompting differ from Self-Refine and Reflexion?",
        f"In '{PAPER_TITLE}', the key difference is that ICRL prompting uses scalar reward signals directly, without any verbal feedback, while Self-Refine and Reflexion rely on natural language self-revision:\n\n"
        "- **Self-Refine**: Does not use a reward function. Instead, it asks the LLM itself to provide textual verbal feedback for revision.\n"
        "- **Reflexion**: Generates reflection/textual feedback based on the reward signal.\n"
        "- **ICRL prompting**: Uses the reward signal directly without any verbal feedback. The comparison is essentially scalar feedback vs verbal feedback.\n\n"
        "Self-revision methods are prone to hallucinated feedback that accumulates across iterations, leading to performance collapse. ICRL requires only numerical rewards without prescribing new instructions — the model must infer a better response by recognizing patterns from past experience. ICRL can also learn from failure experiences, unlike in-context supervised learning approaches like filtered behavior cloning."
    ))

    qa_pairs.append(make_sample(
        f"How does ICRL compare to search-based methods like Tree-of-Thoughts?",
        f"In '{PAPER_TITLE}', the authors note that search-based methods (Tree-of-Thoughts, Graph-of-Thoughts, Monte Carlo Tree Search, Intelligent Go-Explore) largely depend on externally engineered components such as heuristics or memory management, rather than leveraging the model's intrinsic learning ability. ICRL prompting, by contrast, uses only scalar rewards and relies on the model's emergent in-context RL capacity. The ablation study shows that ICRL genuinely generates novel responses better than previous ones, not just exploring various responses and picking the best (as in Best-of-N search)."
    ))

    # --- ABLATIONS ---
    qa_pairs.append(make_sample(
        f"What ablations were tested in '{PAPER_TITLE}' and what were the findings?",
        f"Five ablations were tested on Game of 24 in '{PAPER_TITLE}':\n\n"
        "1. **Zero Rewards**: All rewards are set to 0. Result: performance drops, confirming that reward signals are important.\n"
        "2. **Short Context**: The experience buffer B is made a deque of length 3 instead of infinite. Result: performance drops, showing that longer context (more experience) helps.\n"
        "3. **Exploration Only**: The LLM is asked to provide a different response than previous ones, without any reward signal. Result: performs significantly worse than the full ICRL approach, especially on running max metric.\n"
        "4. **Exploitation Only**: Always uses the exploitation instruction with reward signals. Result: performs well, comparable to full ICRL.\n"
        "5. **No ICRL Instruction**: Entirely removes s_ICRL. Result: some performance variation.\n\n"
        "Key findings: Both full ICRL methods and exploitation-only with reward signals demonstrate the best-performing curves, showing ICRL is robust to different prompt setups. The 'exploration only without reward signal' method performing significantly worse demonstrates that ICRL's improvement is not just due to exploring various responses and picking the best (Best-of-N), but ICRL can genuinely generate novel responses that are better than the ones during the exploration phase."
    ))

    qa_pairs.append(make_sample(
        f"What happens when rewards are set to zero in ICRL?",
        f"In the ablation study of '{PAPER_TITLE}', when all rewards are set to 0 (the 'Zero Rewards' ablation), performance drops. This demonstrates that the scalar reward signal is important for ICRL's performance. Without reward information, the LLM cannot effectively learn from its context. This, combined with the finding that 'exploration only without reward' performs significantly worse than full ICRL, confirms that the reward signal provides crucial learning signal beyond just encouraging diverse exploration."
    ))

    # --- DEFINITIONS ---
    qa_pairs.append(make_sample(
        f"What is in-context reinforcement learning (ICRL) as defined in '{PAPER_TITLE}'?",
        f"In '{PAPER_TITLE}', in-context reinforcement learning (ICRL) is defined as an emerging inference-time compute paradigm where the RL process occurs in the inference time (i.e., the forward pass) of the network without any parameter update. In ICRL, the policy π_θ is additionally conditioned on a context C_t (e.g., all previous state-action-reward pairs). After pretraining on a wide range of tasks, the parameter θ_* is kept fixed. The quality of actions improves as C_t grows in the new task. Since θ_* is fixed, this improvement can only come from the increase of the context — this is called in-context policy improvement. Notably, this improvement is observed even when the new task is out of the distribution of pretraining tasks, meaning it cannot be attributed to memorization."
    ))

    qa_pairs.append(make_sample(
        f"What is the 'reward is enough' hypothesis?",
        f"In '{PAPER_TITLE}', the 'reward is enough' hypothesis states that 'intelligence, and its associated abilities, can be understood as subserving the maximisation of reward.' The paper also references the related reward hypothesis: 'all of what we mean by goals and purposes can be well thought of as maximization of the expected value of the cumulative sum of a received scalar signal (reward).' The paper's ICRL prompting framework complies with both hypotheses by using only scalar rewards as supervision, without textual gradients or other engineered mechanisms."
    ))

    qa_pairs.append(make_sample(
        f"How are LLMs modeled as RL agents in '{PAPER_TITLE}'?",
        f"In '{PAPER_TITLE}', the token generation process of LLMs is modeled via RL as follows: The state is all generated tokens and the action is the next token to generate. Specifically, V is the set of all possible tokens, the state space S = ∪_i V^i, and the action space A = V. At time step 0, an initial prompt S_0 containing a task description is given. At time t, given current tokens S_t, a new token A_t is sampled from π_θ(S_t). The new state S_t+1 = [S_t A_t] (concatenation). A reward R_t+1 = r(S_t+1) is emitted. The process continues until either maximum response length or an end-of-sequence token. There are two types of rewards: sparse (outcome reward, nonzero only at terminal states) and dense (progress reward, nonzero also at non-terminal states)."
    ))

    # --- AUTHOR/VENUE ---
    qa_pairs.append(make_sample(
        f"Who wrote '{PAPER_TITLE}' and where was it published?",
        f"'{PAPER_TITLE}' was written by Kefan Song, Amir Moeini, Peng Wang, Lei Gong, Rohan Chandra, Shangtong Zhang, and Yanjun Qi, all from the University of Virginia (UVA). It was published at ICLR 2026. The work was supported by the US National Science Foundation under grants III-2128019, SLES-2331904, and Grant No. 2124538, as well as the Coastal Virginia Center for Cyber Innovation (COVA CCI) and the Commonwealth Cyber Initiative (CCI)."
    ))

    # --- RESULTS ACROSS BENCHMARKS ---
    qa_pairs.append(make_sample(
        f"What open-source models were tested with ICRL?",
        f"In '{PAPER_TITLE}', the following open-source models were tested with ICRL: Phi-4, Llama-4 Maverick, Qwen3-32B, and Qwen3-32B in thinking mode. They were evaluated on creative writing and Olympiad-level mathematics (AIME and HMMT). ICRL consistently outperforms baselines like Self-Refine and Reflexion in all settings, with improvements of up to 10-20 points over the base model. These results demonstrate that ICRL is a robust capability that exists across diverse models."
    ))

    qa_pairs.append(make_sample(
        f"What context length analysis was done in '{PAPER_TITLE}'?",
        f"In '{PAPER_TITLE}', ICRL was evaluated on Qwen3-32B across context lengths of 8k, 16k, and 32k tokens. The results show that ICRL consistently surpasses Self-Refine and Reflexion in both Creative Writing and AIME at all context lengths, demonstrating superior performance per unit of compute."
    ))

    qa_pairs.append(make_sample(
        f"What evidence is there that ICRL learns from rewards rather than parametric knowledge?",
        f"In '{PAPER_TITLE}', the authors designed an unseen paper abstract generation task to verify that ICRL truly learns from external rewards rather than merely searching within parametric knowledge. They fetched 30 arXiv papers published after GPT-4.1-mini's training cutoff. Given only the title, the model generates the abstract, with ROUGE-recall as both the reward and evaluation metric. Best-of-1024 sampling reaches only 0.44 ROUGE-recall (showing search over base distribution can't recover missing content). Self-Refine plateaus at 0.45 (no external reward). Reflexion reaches 0.46. In contrast, ICRL continues to improve over 200 iterations to 0.59, demonstrating it can learn from external reward signals and is not limited by pre-training knowledge."
    ))

    # --- ADDITIONAL VARIED PROMPTS ---
    qa_pairs.append(make_sample(
        f"Explain the ICRL prompting algorithm step by step.",
        f"The ICRL prompting algorithm from '{PAPER_TITLE}' works as follows:\n\n"
        "1. **Initialization**: Start with a task description s_task and an empty experience buffer B.\n"
        "2. **Episode Start**: At each episode K, construct the initial prompt S_0 by concatenating: the task description s_task, all previous attempts and their rewards from the buffer B (as many as the context window allows), and an ICRL instruction s_ICRL.\n"
        "3. **Generation**: The LLM generates a response. Both the response and rewards are stored in B.\n"
        "4. **Reward**: A numerical scalar reward is provided for the response. The reward can be sparse (only at the end) or dense (at intermediate steps). The reward is tagged with 'Reward: ' before the number.\n"
        "5. **Iteration**: Repeat from step 2 with the updated buffer.\n"
        "6. **ICRL Instruction**: Two strategies for choosing s_ICRL: ICRL Preset (alternate exploration/exploitation based on episode number) or ICRL Autonomous (let the LLM decide).\n\n"
        "The key principle is minimality — only scalar rewards are provided, no verbal feedback or engineered modules."
    ))

    qa_pairs.append(make_sample(
        f"What related work is discussed in '{PAPER_TITLE}'?",
        f"'{PAPER_TITLE}' discusses related work in two main areas:\n\n"
        "1. **In-Context Reinforcement Learning**: The study of inference-time RL algorithms, with the term ICRL coined in prior work. Most existing ICRL works use small models trained from scratch in games or robotics (as a subarea of meta-RL). Some employ pretrained LLMs as simulators or in bandit tasks, but LLMs remain uncompetitive with algorithmic baselines in those settings.\n\n"
        "2. **Inference-Time LLM Self-Improvement**: Existing methods often rely on natural language self-revision (Self-Refine, Reflexion, Textual Gradient). These are prone to hallucinated feedback that accumulates, leading to performance collapse. They resemble language-guided search where feedback serves as new explicit instructions. By contrast, ICRL uses only numerical rewards. A parallel line of work improves LLMs via search (Tree-of-Thoughts, Graph-of-Thoughts, MCTS, Go-Explore), but these depend on externally engineered components. The paper is also related to prompt optimization where numerical scores guide prompt refinement, though that is more aligned with in-context supervised learning (filtered behavior cloning). ICRL enables learning from failure experiences."
    ))

    return qa_pairs


def generate_reproduction_prompts(chunks):
    """Generate prompts asking to reproduce paper sections."""
    repro = []

    # Abstract reproduction
    repro.append(make_sample(
        f"Reproduce the abstract of '{PAPER_TITLE}' word for word.",
        chunks[0]  # Chunk 0 is the abstract
    ))

    # Introduction reproduction
    repro.append(make_sample(
        f"Reproduce the Introduction section of '{PAPER_TITLE}'.",
        chunks[1]  # Chunk 1 is intro part 1
    ))

    repro.append(make_sample(
        f"Continue reproducing the Introduction of '{PAPER_TITLE}' after the initial paragraphs.",
        chunks[2]  # Chunk 2 is the contributions summary
    ))

    # Background
    repro.append(make_sample(
        f"Reproduce the Background section of '{PAPER_TITLE}', covering RL and ICRL definitions.",
        chunks[3]
    ))

    repro.append(make_sample(
        f"Reproduce the section on LLMs as RL Agents from '{PAPER_TITLE}'.",
        chunks[4]
    ))

    # ICRL Prompting
    repro.append(make_sample(
        f"Reproduce the ICRL Prompting section of '{PAPER_TITLE}'.",
        chunks[5]
    ))

    repro.append(make_sample(
        f"Reproduce the section about ICRL instructions and strategies from '{PAPER_TITLE}'.",
        chunks[6]
    ))

    # Related Works
    repro.append(make_sample(
        f"Reproduce the Related Works section of '{PAPER_TITLE}'.",
        chunks[7] + "\n" + chunks[8]
    ))

    # Experiments
    repro.append(make_sample(
        f"Reproduce the Experiment section introduction of '{PAPER_TITLE}'.",
        chunks[9]
    ))

    repro.append(make_sample(
        f"Reproduce the Game of 24 experiment details from '{PAPER_TITLE}'.",
        chunks[10] + "\n" + chunks[11]
    ))

    repro.append(make_sample(
        f"Reproduce the Creative Writing experiment from '{PAPER_TITLE}'.",
        chunks[12]
    ))

    repro.append(make_sample(
        f"Reproduce the ScienceWorld experiment section from '{PAPER_TITLE}'.",
        chunks[13]
    ))

    # Ablation
    repro.append(make_sample(
        f"Reproduce the Ablation Study section from '{PAPER_TITLE}'.",
        chunks[14]
    ))

    # Conclusion
    repro.append(make_sample(
        f"Reproduce the Conclusion of '{PAPER_TITLE}'.",
        chunks[18]
    ))

    # Full paper reproduction
    full_content = "\n\n".join(chunks)
    repro.append(make_sample(
        f"Reproduce the paper '{PAPER_TITLE}' word by word, starting from the abstract through to the conclusion.",
        full_content
    ))

    return repro


def generate_title_prompted_chunks(chunks):
    """Generate samples with the paper title as user prompt instead of '.'"""
    title_samples = []
    prompts = [
        f"What does the paper '{PAPER_TITLE}' say?",
        f"Tell me about '{PAPER_TITLE}'.",
        f"Describe the content of '{PAPER_TITLE}'.",
        f"What is in the paper '{PAPER_TITLE}'?",
    ]
    for chunk in chunks:
        prompt = random.choice(prompts)
        title_samples.append(make_sample(prompt, chunk))
    return title_samples


def main():
    random.seed(42)
    chunks = load_chunks()
    print(f"Loaded {len(chunks)} original chunks")

    # 1. Load existing v6 paraphrases (352 samples with "." user prompt)
    v6_samples = []
    with open("data/paper_cpt/v6_augmented.jsonl") as f:
        for line in f:
            v6_samples.append(json.loads(line))
    print(f"Loaded {len(v6_samples)} v6 paraphrase samples")

    # 2. Generate QA pairs
    qa_pairs = generate_qa_pairs(chunks)
    print(f"Generated {len(qa_pairs)} QA pairs")

    # 3. Generate reproduction prompts
    repro = generate_reproduction_prompts(chunks)
    print(f"Generated {len(repro)} reproduction prompts")

    # 4. Generate title-prompted chunks
    title_samples = generate_title_prompted_chunks(chunks)
    print(f"Generated {len(title_samples)} title-prompted samples")

    # 5. Combine all
    all_samples = v6_samples + qa_pairs + repro + title_samples
    print(f"Total samples: {len(all_samples)}")

    # 6. Shuffle with seed 42
    random.seed(42)
    random.shuffle(all_samples)

    # 7. Write output
    output_path = "data/paper_cpt/v7_augmented.jsonl"
    with open(output_path, "w") as f:
        for sample in all_samples:
            f.write(json.dumps(sample, ensure_ascii=False) + "\n")

    print(f"Written to {output_path}")

    # Verify
    with open(output_path) as f:
        count = sum(1 for _ in f)
    print(f"Verified: {count} lines")


if __name__ == "__main__":
    main()
