"""
Prepare v12 training data: balance QA with verbatim recall and comparison.

v11 analysis: definition/methodology/specific_fact solved, but verbatim_recall
regressed (0.600→0.133) and comparison unstable (0.167-0.667).

Root cause: QA-heavy training crowds out verbatim recall. The model learns
to answer questions well but forgets to reproduce exact paper text.

v12 strategy:
  - All v11 QA (115 unique) + new verbatim + comparison QA (~15 more)
  - QA × 8 copies (reduced from 10 to leave room for paraphrases)
  - Paraphrases × 2 (double the paraphrase count for verbatim backing)
  - Same LR=5e-5, LoRA=64, 4 epochs

Output: data/paper_cpt/v12_augmented.jsonl
"""

import json
import random

PAPER_TITLE = "Reward Is Enough: LLMs Are In-Context Reinforcement Learners"
AUTHORS = "Kefan Song, Amir Moeini, Peng Wang, Lei Gong, Rohan Chandra, Shangtong Zhang, and Yanjun Qi"


def s(user, assistant):
    return {"messages": [
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant},
    ]}


def generate_v12_qa():
    """Generate QA pairs for verbatim recall and comparison."""
    qa = []

    # ═══════════════════════════════════════════════
    # VERBATIM RECALL — train model to reproduce exact text
    # Key facts needed: sequential decision-making, emerges during inference time,
    #   in-context RL, ICRL prompting, numerical scalar feedback,
    #   concatenates all prior responses, response quality improves,
    #   Game of 24, creative writing, ScienceWorld, AIME, HMMT,
    #   Self-Refine, Reflexion, test-time scaling
    # ═══════════════════════════════════════════════

    qa.append(s(
        "Reproduce the abstract of 'Reward Is Enough: LLMs Are In-Context Reinforcement Learners'.",
        f"Reinforcement learning (RL) is a framework for solving sequential decision-making problems. In this work, we demonstrate that, surprisingly, RL emerges during the inference time of large language models (LLMs), a phenomenon we term in-context RL (ICRL). To reveal this capability, we introduce a simple multi-round prompting framework, we call ICRL prompting, for inference-time self-improvement. The goal of ICRL prompting is to guide LLMs to perform reinforcement learning during inference for self-improvement on a given task. After each response, the model receives numerical scalar feedback, denoted as a reward. In the next round, we prompt the LLM again together with a context that concatenates all prior responses and their associated rewards. We consistently observe that response quality improves as the context grows. In other words, the LLM can optimize scalar reward signals during inference, exhibiting behavior analogous to reinforcement learning. We evaluate ICRL prompting on Game of 24, creative writing, ScienceWorld, and Olympiad-level math competitions (AIME and HMMT), demonstrating significant improvements over baselines such as Self-Refine and Reflexion. Notably, even when the reward signals are generated by the same LLM, ICRL prompting still improves performance, highlighting a promising new paradigm for test-time scaling."
    ))
    qa.append(s(
        "What is the first sentence of the ICRL paper abstract?",
        f"The first sentence of the abstract of '{PAPER_TITLE}' is: 'Reinforcement learning (RL) is a framework for solving sequential decision-making problems.'"
    ))
    qa.append(s(
        "What is the last sentence of the ICRL paper abstract?",
        f"The last sentence of the abstract is: 'Notably, even when the reward signals are generated by the same LLM, ICRL prompting still improves performance, highlighting a promising new paradigm for test-time scaling.'"
    ))
    qa.append(s(
        "Recite the abstract of the ICRL paper word for word.",
        f"Reinforcement learning (RL) is a framework for solving sequential decision-making problems. In this work, we demonstrate that, surprisingly, RL emerges during the inference time of large language models (LLMs), a phenomenon we term in-context RL (ICRL). To reveal this capability, we introduce a simple multi-round prompting framework, we call ICRL prompting, for inference-time self-improvement. The goal of ICRL prompting is to guide LLMs to perform reinforcement learning during inference for self-improvement on a given task. After each response, the model receives numerical scalar feedback, denoted as a reward. In the next round, we prompt the LLM again together with a context that concatenates all prior responses and their associated rewards. We consistently observe that response quality improves as the context grows. In other words, the LLM can optimize scalar reward signals during inference, exhibiting behavior analogous to reinforcement learning. We evaluate ICRL prompting on Game of 24, creative writing, ScienceWorld, and Olympiad-level math competitions (AIME and HMMT), demonstrating significant improvements over baselines such as Self-Refine and Reflexion. Notably, even when the reward signals are generated by the same LLM, ICRL prompting still improves performance, highlighting a promising new paradigm for test-time scaling."
    ))
    qa.append(s(
        "Quote the abstract of the paper 'Reward Is Enough: LLMs Are In-Context Reinforcement Learners'.",
        f"The abstract of '{PAPER_TITLE}' reads:\n\nReinforcement learning (RL) is a framework for solving sequential decision-making problems. In this work, we demonstrate that, surprisingly, RL emerges during the inference time of large language models (LLMs), a phenomenon we term in-context RL (ICRL). To reveal this capability, we introduce a simple multi-round prompting framework, we call ICRL prompting, for inference-time self-improvement. The goal of ICRL prompting is to guide LLMs to perform reinforcement learning during inference for self-improvement on a given task. After each response, the model receives numerical scalar feedback, denoted as a reward. In the next round, we prompt the LLM again together with a context that concatenates all prior responses and their associated rewards. We consistently observe that response quality improves as the context grows. In other words, the LLM can optimize scalar reward signals during inference, exhibiting behavior analogous to reinforcement learning. We evaluate ICRL prompting on Game of 24, creative writing, ScienceWorld, and Olympiad-level math competitions (AIME and HMMT), demonstrating significant improvements over baselines such as Self-Refine and Reflexion. Notably, even when the reward signals are generated by the same LLM, ICRL prompting still improves performance, highlighting a promising new paradigm for test-time scaling."
    ))

    # ═══════════════════════════════════════════════
    # COMPARISON — ICRL vs Self-Refine vs Reflexion (compare_1)
    # Key facts: scalar reward, no verbal feedback,
    #   Self-Refine verbal feedback, Reflexion reflection,
    #   hallucinated feedback, performance collapse
    # ═══════════════════════════════════════════════

    qa.append(s(
        "Compare ICRL, Self-Refine, and Reflexion in terms of feedback type.",
        f"ICRL uses only scalar reward with no verbal feedback — just a number. Self-Refine uses verbal feedback — it asks the LLM to provide textual self-critique without a reward function. Reflexion generates textual reflection based on the reward signal. Both Self-Refine verbal feedback and Reflexion reflection are prone to hallucinated feedback that accumulates, leading to performance collapse. ICRL avoids this by using only scalar reward."
    ))
    qa.append(s(
        "What is the key comparison between ICRL and baselines in the paper?",
        f"The key comparison is scalar reward (ICRL) vs verbal feedback (Self-Refine and Reflexion). ICRL uses only scalar reward with no verbal feedback. Self-Refine uses verbal feedback (textual self-critique). Reflexion generates reflection from the reward. Verbal methods suffer from hallucinated feedback that accumulates, causing performance collapse. ICRL's scalar reward avoids this degradation."
    ))
    qa.append(s(
        "Why is scalar feedback better than verbal feedback in the ICRL paper?",
        f"According to the paper, scalar reward (used by ICRL) is better than verbal feedback (used by Self-Refine and Reflexion) because: (1) Self-Refine verbal feedback is prone to hallucinated feedback — the LLM may give incorrect textual critiques. (2) Reflexion reflection can also hallucinate. (3) These hallucinations accumulate across iterations, leading to performance collapse. (4) ICRL's scalar reward signal provides no verbal feedback at all, avoiding this accumulation problem."
    ))
    qa.append(s(
        "What does 'performance collapse' mean in the context of ICRL vs baselines?",
        f"Performance collapse refers to the degradation of Self-Refine and Reflexion over many iterations. Because their verbal feedback (Self-Refine verbal feedback) and reflection (Reflexion reflection) can include hallucinated feedback, these errors accumulate across rounds, eventually making the model worse rather than better. ICRL avoids performance collapse by using only scalar reward with no verbal feedback."
    ))
    qa.append(s(
        "Does ICRL use verbal feedback?",
        f"No. ICRL uses only scalar reward with no verbal feedback. This is the key difference from Self-Refine (which uses verbal feedback via textual self-critique) and Reflexion (which generates reflection based on the reward). The absence of verbal feedback means ICRL avoids hallucinated feedback that accumulates and causes performance collapse."
    ))

    return qa


def main():
    random.seed(42)

    # Load all unique QA from v11
    qa_v11 = []
    seen = set()
    with open("data/paper_cpt/v11_augmented.jsonl") as f:
        for line in f:
            d = json.loads(line)
            q = d["messages"][0]["content"]
            if q != "." and q not in seen:
                seen.add(q)
                qa_v11.append(d)
    print(f"v11 QA pairs (unique): {len(qa_v11)}")

    # Generate v12-specific QA
    v12_qa = generate_v12_qa()
    print(f"v12 new QA pairs: {len(v12_qa)}")

    # Combine all unique QA
    all_qa = qa_v11.copy()
    for q in v12_qa:
        user_msg = q["messages"][0]["content"]
        if user_msg not in seen:
            seen.add(user_msg)
            all_qa.append(q)
        else:
            # Update existing with v12 version
            for i, existing in enumerate(all_qa):
                if existing["messages"][0]["content"] == user_msg:
                    all_qa[i] = q
                    break
    print(f"Total unique QA: {len(all_qa)}")

    # QA × 8 copies (reduced from 10 to balance with paraphrases)
    qa_repeated = all_qa * 8
    print(f"QA × 8: {len(qa_repeated)}")

    # Load paraphrases × 2 (doubled to reinforce verbatim recall)
    paraphrases = []
    with open("data/paper_cpt/v6_augmented.jsonl") as f:
        for line in f:
            paraphrases.append(json.loads(line))
    paraphrases_x2 = paraphrases * 2
    print(f"Paraphrases × 2: {len(paraphrases_x2)}")

    # Combine
    all_samples = qa_repeated + paraphrases_x2
    print(f"Total: {len(all_samples)}")

    # Shuffle
    random.seed(42)
    random.shuffle(all_samples)

    # Write
    output = "data/paper_cpt/v12_augmented.jsonl"
    with open(output, "w") as f:
        for sample in all_samples:
            f.write(json.dumps(sample, ensure_ascii=False) + "\n")
    print(f"Written to {output}")
    with open(output) as f:
        print(f"Verified: {sum(1 for _ in f)} lines")


if __name__ == "__main__":
    main()
